version: '3.7'

services:
  proxy:
    image: nginx:alpine
    ports:
      - '8080:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: 'unless-stopped'
    networks:
      - backend
  server:
    build:
      context: ./
      # target: development-build-stage
      dockerfile: dockerfile
    container_name: sendnest
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
      - /app/node_modules
    restart: 'unless-stopped'
    networks:
      - backend
networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
  cache:
    driver: local